name: Deploy DEV

on:
  push:
    branches:
      - main

jobs:

  deploy:

    environment: dev

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: environments/dev

    env:
      APSTRA_PASS: ${{ secrets.APSTRA_PASS }}
      APSTRA_USER: ${{ vars.APSTRA_USER }}
      APSTRA_URL: ${{ vars.APSTRA_URL }}

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate
      
      - name: Install Python Dependencies
        run: |
          python -m pip install pyyaml

      - name: Network Standards Validation
        run: |
          python ../../scripts/network_standards.py

      - name: Terraform Plan
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan

      - name: Wait for Apstra Analysis
        run: sleep 120
        
      - name: Install Python Dependencies
        run: |
           python -m pip install requests

      - name: Validate Apstra Blueprint
        run: |
           python ../../scripts/apstra_blueprint_validation.py

